### ISSUE TITLE
Promote BackButton MediaQuery to WICG

### ISSUE THREAD

**Issue by fallaciousreasoning** [w3c/WebPlatformWG#128]
The [back button media query](https://github.com/fallaciousreasoning/backbutton-mediaquery/blob/master/explainer.md) is a proposal to allow [web applications](https://www.w3.org/TR/appmanifest/) to determine what UI controls are being displayed by the user agent.

This API is being proposed as a way to eliminate the "double back button" problem (seen [here](images/double-back-button.jpg), on Twitters PWA in the Microsoft store). This problem arises because developers of [`"standalone"`, `"fullscreen"`, and `"minimal-ui"`](https://www.w3.org/TR/appmanifest/#display-modes) apps have no way of determining whether a back button will be provided by the user agent (the browser, OS, or hardware) but are forced to implement their own, to ensure that their app is functional without the browser's UI.

Microsoft has [expressed interest](https://github.com/fallaciousreasoning/backbutton-mediaquery/issues/4) in experimenting with this API (@mustjab), so I'd like to move it to WICG and get some broader feedback. @marcoscaceres @aliams @hober do you have any thoughts?

There's a (newly opened) discourse thread [here](https://discourse.wicg.io/t/proposal-back-button-media-query/3802).

**Comment by LJWatson** [comment]
Thanks for raising this request @fallaciousreasoning.

The Web Platform WG is due to close and has been replaced by the [Web Applications (WebApps) WG](https://w3c.github.io/webappswg). If you could raise this request via the [WebApps repo](https://github.com/w3c/webappswg/issues/new), that would be great.

Before you do, take a look at the request to [migrate Web Share to WebApps](https://github.com/w3c/web-share/issues/99). It'll give you an idea of the sort of information that'll be needed (use cases, implementation commitments, compatibility risks, technical constraints, accessibility/internationalisation/privacy/security considerations etc.).
