### ISSUE TITLE
I support the proposal to mark previous versions of HTML as obsolete.

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/WebPlatformWG#91]
This is an important accessibility issue, because of the improvements with each version.

**Comment by LJWatson** [comment]
Without preventing anyone from using older versions of HTML and XHTML, this will make it clear that these previous versions have been superseded, and will provide a clear signpost from each old specification through to the current version. Making it easy for authors to confidently identify the authoritative version makes sense to me.

**Comment by nickirios** [comment]
Please do. I'm sure it would help clear up any confusion, which would make it easier for people to use it correctly.

**Comment by akuckartz** [comment]
:+1:

**Comment by glowingsword** [comment]
Please do it. This is very important decision, which will save people from confusion in different html standards, and help the browser manufacturer in future to refuse to support outdated standards.

**Comment by cookiecrook** [comment]
Not just HTML, but abandoned Recs and Editor’s drafts of all specs. For example, I regularly get emails from people excited about IndieUI, even though the we abandoned that approach years ago.

**Comment by notabene** [comment]
Where do we vote?

**Comment by LJWatson** [comment]
@cookiecrook requests can be made by any WG to obsolete or rescind any Recommendation. Not sure how it works for specs like IndieUI that didn't make Rec - but one option might be to publish a WD update with this information in the status perhaps.

notabene the vote is made by the AC, but the W3C wants to know what authors/developers across the web community think. This issue is a good way to do that (and to encourage other people to express their opinions about the proposal too).

**Comment by xfq** [comment]
Can this issue be closed now, given previous XHTML/HTML Recommendations are now Superseded?

**Comment by chaals** [comment]
yep.
